#ifndef DEFINES_H
# define DEFINES_H

/* SETTINGS */
# define FRACTOL_WINDOW_TITLE "Fract'ol"

# define FRACTOL_ITERATION_DEFAULT_LIMIT  16
# define FRACTOL_ITERATIONS_CHANGE        2
# define FRACTOL_ITERATIONS_MIN           2
# define FRACTOL_ITERATIONS_MAX           256

# define FRACTOL_ZOOM_DEFAULT             300.
# define FRACTOL_ZOOM_INCREASE_ASPECT     1.05
# define FRACTOL_ZOOM_DECREASE_ASPECT     0.95

# define FRACTOL_ZOOM_SAME_ITERATION_LIMIT_STEP 5

# define FRACTOL_SET_NUMBER_MIN       1
# define FRACTOL_SET_NUMBER_MAX       4

# define FRACTOL_THREADS_NUMBER       64

/* ON/OFF FOR EFFECT */
// # define DEBUG

#endif //!DEFINES_H
